package vedadracuni;
// Generated Apr 5, 2020 5:52:22 PM by Hibernate Tools 4.3.1


import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Vedad generated by hbm2java
 */
@Entity
@Table(name="vedad"
    ,catalog="rezije"
)
public class Vedad  implements java.io.Serializable {
    @Transient
    private PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);


@Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
     private Integer id;
@Column(name="datum", precision=22, scale=0)
     private String datum;
@Column(name="struja", precision=22, scale=0)
     private Double struja;
@Column(name="oki", precision=22, scale=0)
     private Double oki;
@Column(name="komunalije", precision=22, scale=0)
     private Double komunalije;
@Column(name="telemach", precision=22, scale=0)
     private Double telemach;
@Column(name="plin", precision=22, scale=0)
     private Double plin;
@Column(name="voda", precision=22, scale=0)
     private Double voda;
@Column(name="kreditna_kartica", precision=22, scale=0)
     private Double kreditnaKartica;
@Column(name="ukupno", precision=22, scale=0)
      private String ukupno;

    public Vedad() {
    }

    public Vedad(String datum, Double struja, Double oki, Double komunalije, Double telemach, Double plin, Double voda, Double kreditnaKartica,String ukupno) {
       this.datum = datum;
       this.struja = struja;
       this.oki = oki;
       this.komunalije = komunalije;
       this.telemach = telemach;
       this.plin = plin;
       this.voda = voda;
       this.kreditnaKartica = kreditnaKartica;
        this.ukupno = ukupno;
    }
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        Integer oldId = this.id;
        this.id = id;
        changeSupport.firePropertyChange("id", oldId, id);
    }
    
    public String getDatum() {
        return this.datum;
    }
    
    public void setDatum(String datum) {
       String oldDatum = this.datum;
        this.datum = datum;
        changeSupport.firePropertyChange("datum", oldDatum, datum);
    }


 

    
    public Double getStruja() {
        return this.struja;
    }
    
    public void setStruja(Double struja) {
        Double oldStruja = this.struja;
        this.struja = struja;
        changeSupport.firePropertyChange("struja", oldStruja, struja);
    }

    
    public Double getOki() {
        return this.oki;
    }
    
    public void setOki(Double oki) {
        Double oldOki = this.oki;
        this.oki = oki;
        changeSupport.firePropertyChange("oki", oldOki, oki);
    }

    
    public Double getKomunalije() {
        return this.komunalije;
    }
    
    public void setKomunalije(Double komunalije) {
        Double oldKomunalije = this.komunalije;
        this.komunalije = komunalije;
        changeSupport.firePropertyChange("komunalije", oldKomunalije, komunalije);
    }

    
    public Double getTelemach() {
        return this.telemach;
    }
    
    public void setTelemach(Double telemach) {
        Double oldTelemach = this.telemach;
        this.telemach = telemach;
        changeSupport.firePropertyChange("telemach", oldTelemach, telemach);
    }

    
    public Double getPlin() {
        return this.plin;
    }
    
    public void setPlin(Double plin) {
        Double oldPlin = this.plin;
        this.plin = plin;
        changeSupport.firePropertyChange("plin", oldPlin, plin);
    }

    
    public Double getVoda() {
        return this.voda;
    }
    
    public void setVoda(Double voda) {
        Double oldVoda = this.voda;
        this.voda = voda;
        changeSupport.firePropertyChange("voda", oldVoda, voda);
    }

    
    public Double getKreditnaKartica() {
        return this.kreditnaKartica;
    }
    
    public void setKreditnaKartica(Double kreditnaKartica) {
        Double oldKreditnaKartica = this.kreditnaKartica;
        this.kreditnaKartica = kreditnaKartica;
        changeSupport.firePropertyChange("kreditnaKartica", oldKreditnaKartica, kreditnaKartica);
    }
    public String getUkupno() {
        return this.ukupno;
    }
    
    public void setukupno(String ukupno) {
        this.ukupno = ukupno;
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }



}


